name: main
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 15, 16, 17, 18]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}.x

      - name: Use cached node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: nodeModules-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}

      - name: Upgrade npm for older versions of Node.js
        run: npm install -g npm@^8.5
        env:
          CI: true

      - name: Install dependencies
        run: npm install
        env:
          CI: true

      - name: Test
        run: npm test
        env:
          CI: true

      - name: Send coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info

      - name: Build
        run: npm run build
        env:
          CI: true

      - name: Link
        run: npm link
        env:
          CI: true

      - name: Test Build
        run: npm run build:test
        env:
          CI: true
